name: test
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

      - run: |
          cat <<'EOS' > github.json
          ${{ toJSON(github) }}
          EOS

      - uses: actions/upload-artifact@v4
        with:
          name: github.json
          path: github.json

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - run: echo pull_request
